name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    # runner:  GitHub provides Ubuntu Linux, Microsoft Windows, and macOS
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-image
        with:
          version: v0.0.5
          username: ${{ secrets.GITLAB_USERNAME }}
          token: ${{ secrets.GITLAB_TOKEN }}
          registryurl: ${{ secrets.GITLAB_REGISTRY_URL }}
